version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: adm1234
      MYSQL_DATABASE: market_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  spring-app:
    image: mikhaelwellman28/dummy-genai
    container_name: dummy-genai
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/market_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: adm1234

volumes:
  mysql-data: